name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Nodejs digitalocean application.
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            git clone git@github.com:kanin-kearpimy/nextjs-github-action.git
            cd nextjs-github-action
            npm start
            echo 'Deployment successfully to digital ocean.'
  # check-file-tree-and-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #     - run: npm install next
  #     - run: npm run build
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: ls -la
